[package]
name = "local_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Storage", "Window"] }